import type { NextPage } from "next";
import Head from "next/head";
import { Controller } from "../components/Controller";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next-Flls</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Controller />
    </div>
  );
};

export default Home;
